[package]
name = "bpftop-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
aya-bpf = "0.1"
aya-log-ebpf = "0.1"
bpftop-common = { path = "../bpftop-common", default-features = false }

[[bin]]
name = "bpftop-ebpf"
path = "src/main.rs"
